# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "neo4j_helper"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Ehrlich"]
  s.date = "2012-01-25"
  s.description = "Attemting to minimize the syntactical learning curve from other ORMs"
  s.email = "peter.i.ehrlich@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/neo4j_helper.rb",
    "lib/neo4j_helper/accepts_hash_for.rb",
    "lib/neo4j_helper/misc.rb",
    "lib/neo4j_helper/serialize.rb",
    "neo4j_helper.gemspec",
    "test/helper.rb",
    "test/test_neo4j_helper.rb"
  ]
  s.homepage = "http://github.com/pehrlich/neo4j_helper"
  s.licenses = ["WTFPL"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.13"
  s.summary = "Making neo4j gem mo' spiffy for your data-nomming needs"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

